dados <- read.csv2("dataset/dados_DL2016.csv")

dados$A <- factor(dados$A)
dados$B <- factor(dados$B)
dados$OF <- factor(dados$OF)
dados$OH <- factor(dados$OH)
dados$IS <- ordered(dados$IS)
dados$SUP <- factor(dados$SUP)
dados$LADO <- factor(dados$LADO)
dados$Falha <- factor(dados$Falha)
dados$TOTAL <- ordered(dados$TOTAL)
